/**
 * Gotowe modele wiat, zadaszeń i pergoli — punkt wyjścia do własnych zmian.
 *
 * DLACZEGO TO NIE JEST KATALOG PRODUKTÓW
 * --------------------------------------
 * Nikt nie stawia wiaty „takiej jak w programie". Te modele mają zaoszczędzić
 * kwadrans wpisywania: podstawiają wymiary i przekroje spotykane w takich
 * konstrukcjach najczęściej, a potem i tak trzeba je dopasować do działki,
 * do auta, które ma tam stać, i do projektu konstrukcyjnego.
 *
 * Każdy model musi przechodzić obliczenia bez ostrzeżeń — pilnuje tego test.
 * Jeśli dokładasz nowy, sprawdź prześwit pod okapem, minimalny spadek dla
 * pokrycia i to, czy najdłuższy element mieści się w belce handlowej.
 */

import type { ShelterInput, ShelterKind } from './shelter'
import { defaultShelter } from './shelter'

/** Jeden gotowy model do wczytania. */
export interface ShelterPreset {
  id: string
  /** Nazwa na kafelku. */
  nazwa: string
  /** Jedno zdanie o tym, do czego to jest. */
  opis: string
  /** Co model zmienia względem wartości domyślnych. */
  dane: Partial<ShelterInput> & { kind: ShelterKind }
}

export const SHELTER_PRESETS: ShelterPreset[] = [
  // ---------- wiaty wolnostojące ----------
  {
    id: 'wiata-jedno-auto',
    nazwa: 'Garażowa na jedno auto',
    opis: 'Najczęstsza wiata przy domu. Spadek w tył, żeby woda nie lała się na podjazd.',
    dane: {
      kind: 'wiata',
      shape: 'jednospadowy',
      width: 3500,
      length: 5500,
      pitchDeg: 12,
      clearHeight: 2400,
      eavesFront: 300,
      eavesSide: 300,
      postSpacingMax: 2800,
      postSection: { b: 140, h: 140 },
      beamSection: { b: 120, h: 180 },
      rafterSection: { b: 80, h: 160 },
      rafterSpacingMax: 900,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 600,
      braceSection: { b: 100, h: 100 },
      covering: 'blacha-trapezowa',
      battenSpacing: 900,
      battenSection: { b: 50, h: 100 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'podstawa-u',
      footingSize: 400,
      footingDepth: 900,
      hasGutters: true,
    },
  },
  {
    id: 'wiata-dwa-auta',
    nazwa: 'Garażowa na dwa auta',
    opis: 'Dwuspadowa, bo przy tej szerokości jednospadowa robi się bardzo wysoka z tyłu.',
    dane: {
      kind: 'wiata',
      shape: 'dwuspadowy',
      width: 6000,
      length: 5500,
      pitchDeg: 20,
      clearHeight: 2400,
      eavesFront: 400,
      eavesSide: 400,
      postSpacingMax: 2800,
      postSection: { b: 140, h: 140 },
      beamSection: { b: 140, h: 200 },
      rafterSection: { b: 80, h: 180 },
      rafterSpacingMax: 900,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 700,
      braceSection: { b: 100, h: 100 },
      covering: 'blachodachowka',
      battenSpacing: 350,
      battenSection: { b: 40, h: 60 },
      counterBattenSection: { b: 25, h: 50 },
      hasMembrane: true,
      hasSlats: false,
      postBase: 'podstawa-u',
      footingSize: 400,
      footingDepth: 900,
      hasGutters: true,
    },
  },
  {
    id: 'wiata-na-drewno',
    nazwa: 'Na drewno opałowe',
    opis: 'Wąska i niska, z dłuższym okapem od frontu — drewno ma stać w suchym.',
    dane: {
      kind: 'wiata',
      shape: 'jednospadowy',
      width: 2500,
      length: 4000,
      pitchDeg: 15,
      clearHeight: 2200,
      eavesFront: 500,
      eavesSide: 300,
      postSpacingMax: 2000,
      postSection: { b: 120, h: 120 },
      beamSection: { b: 100, h: 160 },
      rafterSection: { b: 60, h: 140 },
      rafterSpacingMax: 800,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 500,
      braceSection: { b: 80, h: 80 },
      covering: 'blacha-trapezowa',
      battenSpacing: 800,
      battenSection: { b: 40, h: 80 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'podstawa-u',
      footingSize: 300,
      footingDepth: 800,
      hasGutters: false,
    },
  },
  {
    id: 'wiata-gospodarcza',
    nazwa: 'Gospodarcza na maszyny',
    opis: 'Duża hala bez ścian: wysoki prześwit i belka kalenicowa na własnych słupach.',
    dane: {
      kind: 'wiata',
      shape: 'dwuspadowy',
      width: 8000,
      length: 12000,
      pitchDeg: 25,
      clearHeight: 3000,
      eavesFront: 500,
      eavesSide: 500,
      postSpacingMax: 3000,
      postSection: { b: 160, h: 160 },
      beamSection: { b: 160, h: 220 },
      rafterSection: { b: 80, h: 200 },
      rafterSpacingMax: 900,
      hasRidgeBeam: true,
      ridgeSection: { b: 160, h: 220 },
      hasBraces: true,
      braceArm: 800,
      braceSection: { b: 120, h: 120 },
      covering: 'blacha-trapezowa',
      battenSpacing: 900,
      battenSection: { b: 50, h: 100 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'kotwa-regulowana',
      footingSize: 500,
      footingDepth: 1000,
      hasGutters: true,
    },
  },

  // ---------- zadaszenia przyścienne ----------
  {
    id: 'zadaszenie-tarasu',
    nazwa: 'Zadaszenie tarasu',
    opis: 'Poliwęglan, żeby pod spodem nie zrobiło się ciemno. Spadek od ściany budynku.',
    dane: {
      kind: 'zadaszenie',
      shape: 'jednospadowy',
      width: 3500,
      length: 6000,
      pitchDeg: 15,
      clearHeight: 2600,
      eavesFront: 300,
      eavesSide: 300,
      postSpacingMax: 2500,
      postSection: { b: 140, h: 140 },
      beamSection: { b: 120, h: 200 },
      rafterSection: { b: 80, h: 160 },
      rafterSpacingMax: 900,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 600,
      braceSection: { b: 100, h: 100 },
      covering: 'poliweglan',
      battenSpacing: 700,
      battenSection: { b: 50, h: 100 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'kotwa-wklejana',
      footingSize: 400,
      footingDepth: 900,
      hasGutters: true,
    },
  },
  {
    id: 'zadaszenie-wejscia',
    nazwa: 'Zadaszenie wejścia',
    opis: 'Mały daszek nad drzwiami, na dwóch słupach. Stromszy, żeby śnieg z niego schodził.',
    dane: {
      kind: 'zadaszenie',
      shape: 'jednospadowy',
      width: 1500,
      length: 2500,
      pitchDeg: 20,
      clearHeight: 2300,
      eavesFront: 250,
      eavesSide: 250,
      postSpacingMax: 2500,
      postSection: { b: 120, h: 120 },
      beamSection: { b: 100, h: 160 },
      rafterSection: { b: 60, h: 140 },
      rafterSpacingMax: 800,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 400,
      braceSection: { b: 80, h: 80 },
      covering: 'poliweglan',
      battenSpacing: 700,
      battenSection: { b: 40, h: 80 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'kotwa-wklejana',
      footingSize: 300,
      footingDepth: 900,
      hasGutters: true,
    },
  },
  {
    id: 'zadaszenie-podjazdu',
    nazwa: 'Carport przy ścianie',
    opis: 'Miejsce postojowe dostawione do domu. Płaski spadek, blacha trapezowa.',
    dane: {
      kind: 'zadaszenie',
      shape: 'jednospadowy',
      width: 3000,
      length: 6000,
      pitchDeg: 10,
      clearHeight: 2500,
      eavesFront: 400,
      eavesSide: 400,
      postSpacingMax: 3000,
      postSection: { b: 140, h: 140 },
      beamSection: { b: 120, h: 200 },
      rafterSection: { b: 80, h: 160 },
      rafterSpacingMax: 900,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 600,
      braceSection: { b: 100, h: 100 },
      covering: 'blacha-trapezowa',
      battenSpacing: 900,
      battenSection: { b: 50, h: 100 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'podstawa-u',
      footingSize: 400,
      footingDepth: 900,
      hasGutters: true,
    },
  },
  {
    id: 'zadaszenie-gospodarcze',
    nazwa: 'Przybudówka gospodarcza',
    opis: 'Wąski dach przy ścianie stodoły albo garażu — na rowery, drewno, narzędzia.',
    dane: {
      kind: 'zadaszenie',
      shape: 'jednospadowy',
      width: 2000,
      length: 4000,
      pitchDeg: 12,
      clearHeight: 2200,
      eavesFront: 300,
      eavesSide: 300,
      postSpacingMax: 2000,
      postSection: { b: 120, h: 120 },
      beamSection: { b: 100, h: 160 },
      rafterSection: { b: 60, h: 140 },
      rafterSpacingMax: 800,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 450,
      braceSection: { b: 80, h: 80 },
      covering: 'blacha-trapezowa',
      battenSpacing: 800,
      battenSection: { b: 40, h: 80 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'podstawa-u',
      footingSize: 300,
      footingDepth: 800,
      hasGutters: false,
    },
  },

  // ---------- pergole ----------
  {
    id: 'pergola-taras',
    nazwa: 'Pergola nad tarasem',
    opis: 'Szczebliny zamiast pokrycia: dają cień, przepuszczają deszcz i światło.',
    dane: {
      kind: 'pergola',
      shape: 'jednospadowy',
      width: 3500,
      length: 5000,
      pitchDeg: 4,
      clearHeight: 2500,
      eavesFront: 200,
      eavesSide: 200,
      postSpacingMax: 2500,
      postSection: { b: 140, h: 140 },
      beamSection: { b: 120, h: 180 },
      rafterSection: { b: 80, h: 160 },
      rafterSpacingMax: 800,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 500,
      braceSection: { b: 90, h: 90 },
      covering: 'brak',
      hasMembrane: false,
      hasSlats: true,
      slatSpacing: 250,
      slatSection: { b: 40, h: 90 },
      postBase: 'podstawa-u',
      footingSize: 350,
      footingDepth: 900,
      hasGutters: false,
    },
  },
  {
    id: 'pergola-zadaszona',
    nazwa: 'Pergola z poliwęglanem',
    opis: 'Ta sama rama, ale kryta — pod nią da się usiąść też w deszczu.',
    dane: {
      kind: 'pergola',
      shape: 'jednospadowy',
      width: 3500,
      length: 5000,
      pitchDeg: 8,
      clearHeight: 2500,
      eavesFront: 250,
      eavesSide: 250,
      postSpacingMax: 2500,
      postSection: { b: 140, h: 140 },
      beamSection: { b: 120, h: 180 },
      rafterSection: { b: 80, h: 160 },
      rafterSpacingMax: 800,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 500,
      braceSection: { b: 90, h: 90 },
      covering: 'poliweglan',
      battenSpacing: 700,
      battenSection: { b: 50, h: 100 },
      hasMembrane: false,
      hasSlats: false,
      postBase: 'podstawa-u',
      footingSize: 350,
      footingDepth: 900,
      hasGutters: true,
    },
  },
  {
    id: 'pergola-ogrodowa',
    nazwa: 'Pergola ogrodowa',
    opis: 'Kwadratowa, na czterech słupach, wolno stojąca w głębi działki.',
    dane: {
      kind: 'pergola',
      shape: 'jednospadowy',
      width: 3000,
      length: 3000,
      pitchDeg: 5,
      clearHeight: 2400,
      eavesFront: 300,
      eavesSide: 300,
      postSpacingMax: 3000,
      postSection: { b: 140, h: 140 },
      beamSection: { b: 120, h: 180 },
      rafterSection: { b: 70, h: 140 },
      rafterSpacingMax: 700,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 500,
      braceSection: { b: 90, h: 90 },
      covering: 'brak',
      hasMembrane: false,
      hasSlats: true,
      slatSpacing: 200,
      slatSection: { b: 40, h: 90 },
      postBase: 'podstawa-u',
      footingSize: 350,
      footingDepth: 900,
      hasGutters: false,
    },
  },
  {
    id: 'pergola-nad-sciezka',
    nazwa: 'Pergola nad przejściem',
    opis: 'Długa i wąska, nad ścieżką albo podjazdem. Słupy gęściej, bo belki są cieńsze.',
    dane: {
      kind: 'pergola',
      shape: 'jednospadowy',
      width: 2500,
      length: 8000,
      pitchDeg: 3,
      clearHeight: 2400,
      eavesFront: 200,
      eavesSide: 200,
      postSpacingMax: 2000,
      postSection: { b: 120, h: 120 },
      beamSection: { b: 100, h: 180 },
      rafterSection: { b: 70, h: 140 },
      rafterSpacingMax: 700,
      hasRidgeBeam: false,
      hasBraces: true,
      braceArm: 450,
      braceSection: { b: 80, h: 80 },
      covering: 'brak',
      hasMembrane: false,
      hasSlats: true,
      slatSpacing: 300,
      slatSection: { b: 40, h: 90 },
      postBase: 'podstawa-u',
      footingSize: 300,
      footingDepth: 900,
      hasGutters: false,
    },
  },
]

/** Modele dla wybranego rodzaju konstrukcji. */
export function presetsFor(kind: ShelterKind): ShelterPreset[] {
  return SHELTER_PRESETS.filter((p) => p.dane.kind === kind)
}

/**
 * Wczytuje model, zostawiając ustawienia, które nie opisują konstrukcji, tylko
 * sposób pracy: skąd bierzemy drewno, jaki naddatek na docięcie i czy liczymy
 * impregnat. Ktoś, kto raz przestawił się na drewno z tartaku, nie chce tego
 * ustawiać od nowa przy każdym modelu.
 */
export function applyPreset(preset: ShelterPreset, biezacy: ShelterInput): ShelterInput {
  return {
    ...defaultShelter(),
    ...preset.dane,
    stockMode: biezacy.stockMode,
    stockLengths: [...biezacy.stockLengths],
    cutAllowance: biezacy.cutAllowance,
    hasImpregnation: biezacy.hasImpregnation,
  }
}
